STONES_COLUMNS = [
    "stone_id",
    "kurgin_import_id",
    "report_number",
    "stock_number",
    "lab",
    "shape",
    "weight",
    "color",
    "clarity",
    "cut",
    "polish",
    "symmetry",
    "fluorescence",
    "measurements",
    "min_diameter",
    "max_diameter",
    "depth_mm",
    "kurgin_score",
    "score_status",
    "catalog_section",
    "status",
    "availability_status",
    "shipment_id",
    "import_id",
    "source_file",
    "imported_at",
    "supplier_name",
    "shipment_date",
    "currency",
    "published_price",
    "admin_note",
    "validation_status",
    "validation_message",
    "warning_status",
    "warning_message",
]

SHIPMENTS_COLUMNS = [
    "shipment_id",
    "import_id",
    "supplier_name",
    "shipment_date",
    "shipment_name",
    "currency",
    "total_purchase_cost",
    "advance_paid",
    "payment_comment",
    "comment",
    "original_filename",
    "stored_filename",
    "source_file_path",
    "created_at",
]

IMPORT_LOG_COLUMNS = [
    "import_id",
    "source_file",
    "original_filename",
    "stored_filename",
    "imported_at",
    "excel_template_version",
    "rows_total",
    "rows_saved",
    "rows_not_saved",
    "warnings_count",
    "conflicts_count",
    "status",
    "message",
]

REQUIRED_SHEETS = ["Results", "Details", "Issues", "System"]
